---
title: "NEFSC R Shiny Book"
author: "R shiny group"
date: "`r format(Sys.Date(), '%e %B %Y')`"
site: bookdown::bookdown_site
knit: "bookdown::render_book"
output: gitbook
always_allow_html: true
documentclass: book
#bibliography: ["bibliography/xxx.bib","packages.bib"]
biblio-style: apalike
link-citations: true
github-repo: kimberly-bastille/shiny-book
description: "This book documents nothing yet"
---

# Introduction
This book was compiled by the NEFSC R [shiny group](#group) to showcase how we have used [R shiny](https://shiny.rstudio.com/) apps to enhance our work. Each chapter describes a different shiny app developed at the Northeast Fisheries Center. Many of the apps shared here are under ongoing development and the purpose of this book is to share our work and the lessons we've learned through developing these apps. 

## Getting started

All apps developed by the shiny group are located the internal server `shiny1`. Anyone who is inside of the NEFSC firewall (either physically or via VPN) should be able to run any of the apps developed by the shiny group. Login credentials are required to contribute or collaborate on the development of an app. Please contact ITD for help in setting up an account and providing access.

Each app developed by a particular user will reside in a unique folder under their account name. The following url format is used to run any app `http://shiny1.nefsc.noaa.gov:3838/userName/appName`

A shiny app can be developed 

* locally (and then copied to the server) or
* directly on the server. Rstudio is installed on the shiny server to help with live testing of an app.











